baseURL = 'https://n0t-f0ur13r.github.io/'
languageCode = 'en-us'
title = 'Josué Leiva'
theme = 'PaperMod'

[params]
    defaultTheme = "auto" # Oscuro/Claro automático
    ShowReadingTime = true
    ShowShareButtons = false
    # Tu perfil lateral
    [params.profileMode]
        enabled = true
        title = "Josué Leiva"
        subtitle = "Civil Telematics Engineering Student"
        imageUrl = "https://github.com/n0t-f0ur13r.png" # Usa tu foto de GitHub auto
        imageTitle = "Josué Leiva"

        [[params.profileMode.buttons]]
            name = "Projects"
            url = "/projects"
        [[params.profileMode.buttons]]
            name = "Garden"
            url = "/garden"
        [[params.profileMode.buttons]]
            name = "CV"
            url = "/cv.pdf"

    # Redes sociales (Iconos)
    [[params.socialIcons]]
        name = "github"
        url = "https://github.com/n0t-f0ur13r"
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://linkedin.com/in/josuenicolas"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20
  [[menu.main]]
    identifier = "garden"
    name = "Garden"
    url = "/garden/"
    weight = 30
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 40
